# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded configuration!"

# Colors
set -g default-terminal "screen-256color"
set -sa terminal-overrides ",xterm-kitty:RGB"

# Set leader to Ctrl+S for easier access
set -g prefix2 C-s

# Eliminate delay after pressing Escape
set -s escape-time 0

# Status bar
set -g status-position top
set -g status-left-length 200
set -g status-right-length 200

# Start windows and panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows automatically
set -g renumber-windows on

# Enable mouse
set -g mouse on

# Vim workflow
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel \
  'if [ -n "$WAYLAND_DISPLAY" ]; then wl-copy; else xclip -in -selection clipboard; fi'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel \
  'if [ -n "$WAYLAND_DISPLAY" ]; then wl-copy; else xclip -in -selection clipboard; fi'

# Navigation
bind -r ^ last-window
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Tmux sessionizer
#bind -r f neww '~/.local/bin/tmux-sessionizer'
#set -g update-environment "PROJECT"
#bind -r P run-shell '~/.local/bin/tmux-sessionizer $PROJECT'

# Source local configuration (if any)
if-shell "[ -f ~/.tmux.conf.local ]" "source-file ~/.tmux.conf.local"
