# BEGIN_KITTY_THEME
# Base2Tone Pool Dark
include current-theme.conf
# END_KITTY_THEME

# Bell - silence
enable_audio_bell	no

# Scrollback - increase; default = 2000
scrollback_lines	10000

# Tabs
tab_bar_style	powerline
tab_bar_edge	bottom
tab_bar_min_tabs	1
map Ctrl+Shift+T new_tab_with_cwd

# Window decorations
hide_window_decorations	no

# Window transparency
background_opacity	1.00

# Window multiplexing
enabled_layouts	splits
map ctrl+shift+enter launch --cwd=current --location=split
map ctrl+shift+alt+enter layout_action rotate
map ctrl+shift+h neighboring_window left
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+l neighboring_window right

include local.conf
