
# === LOOKS ============================================================

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME

# Transparency
background_opacity 1.00

hide_window_decorations yes

tab_bar_style powerline

# # Minimum number of tabs to enable tab bar
# tab_bar_min_tabs 1

# Cursor
cursor_trail 1

# CUSTOM SHADERS

# Cursor
# custom_shaders cursor-trail-blaze
# custom_shaders cursor-trail-lightning

# Filter
# custom_shaders bloom
# custom_shaders crt
# custom_shaders crt-blue

# Tabs
# custom_shaders tab-change
# custom_shaders focus-highlight


# === BEHAVIOR ==========================================================

# Bell
enable_audio_bell no

# Scrollback (default = 2000)
scrollback_lines 10000

# Open new OS windows in current working directory
map ctrl+shift+n new_os_window_with_cwd

# Open new tabs in current working directory
map Ctrl+Shift+t new_tab_with_cwd

# Open new windows in current working directory
# map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+enter launch --cwd=current --location=split

# Window multiplexing layouts enabled
enabled_layouts splits, tall, fat, grid

# === KEYMAPS ==========================================================

# Rotate the current window split
map ctrl+shift+alt+enter layout_action rotate

# Navigate windows
map ctrl+shift+left neighboring_window left
map ctrl+shift+down neighboring_window down
map ctrl+shift+up neighboring_window up
map ctrl+shift+right neighboring_window right

# Move active window
map ctrl+shift+alt+left move_window left
map ctrl+shift+alt+down move_window down
map ctrl+shift+alt+up move_window up
map ctrl+shift+alt+right move_window left

# Scroll terminal lines
map ctrl+shift+j scroll_line_down
map ctrl+shift+k scroll_line_up


# === LOCAL CONFIG ======================================================

include local.conf
